apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp #application name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victoorraphael/argo-lab.git
    targetRevision: HEAD
    path: infra/dev
  destination:
    server: https://kubernetes.default.svc #where argo is installed
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
